name: preparatorio_concursos
description: Aplicativo multiplataforma para preparação de concursos públicos.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  http: ^1.3.0
  shared_preferences: ^2.0.6
  in_app_purchase: ^3.2.1
  file_picker: ^10.0.0
  path_provider: ^2.1.2
  syncfusion_flutter_pdf: ^24.1.41
  flutter_pdfview: ^1.3.2
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_commons: ^0.11.0
  image: ^4.1.3
  collection: ^1.18.0
  table_calendar: ^3.0.9
  intl: ^0.18.1

  flutter_dotenv: ^5.1.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/
    - assets/fonts/
    - assets/i18n/
    - lib/core/prompts/
    - lib/core/prompts/edital_analysis/
    - .env