// Mocks generated by Mockito 5.4.5 from annotations
// in preparatorio_concursos/test/core/utils/pdf_processor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:preparatorio_concursos/core/utils/pdf_optimizer.dart' as _i2;
import 'package:preparatorio_concursos/core/utils/pdf_scanner_detector.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PdfOptimizer].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfOptimizer extends _i1.Mock implements _i2.PdfOptimizer {
  MockPdfOptimizer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> processLargePdf(
    _i4.Uint8List? pdfBytes, {
    int? chunkSize = 20,
    bool? extractTables = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #processLargePdf,
              [pdfBytes],
              {#chunkSize: chunkSize, #extractTables: extractTables},
            ),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(
                  #processLargePdf,
                  [pdfBytes],
                  {#chunkSize: chunkSize, #extractTables: extractTables},
                ),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<List<String>> processPdfsInParallel(
    List<_i4.Uint8List>? pdfBytesList, {
    int? maxConcurrent = 2,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #processPdfsInParallel,
              [pdfBytesList],
              {#maxConcurrent: maxConcurrent},
            ),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);
}

/// A class which mocks [PdfScannerDetector].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfScannerDetector extends _i1.Mock
    implements _i6.PdfScannerDetector {
  MockPdfScannerDetector() {
    _i1.throwOnMissingStub(this);
  }
}
