// Mocks generated by Mockito 5.4.5 from annotations
// in preparatorio_concursos/test/unit/services/api_config_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:preparatorio_concursos/core/data/services/interfaces/secure_storage_service_interface.dart'
    as _i2;
import 'package:preparatorio_concursos/core/utils/logger.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ISecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockISecureStorageService extends _i1.Mock
    implements _i2.ISecureStorageService {
  MockISecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveSecure(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#saveSecure, [key, value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getSecure(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getSecure, [key]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> deleteSecure(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSecure, [key]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAllSecure() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllSecure, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> containsKeySecure(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKeySecure, [key]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, String>> getAllSecure() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSecure, []),
            returnValue: _i3.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i3.Future<Map<String, String>>);

  @override
  String hashPassword(String? password, String? salt) =>
      (super.noSuchMethod(
            Invocation.method(#hashPassword, [password, salt]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#hashPassword, [password, salt]),
            ),
          )
          as String);

  @override
  String generateSalt() =>
      (super.noSuchMethod(
            Invocation.method(#generateSalt, []),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#generateSalt, []),
            ),
          )
          as String);

  @override
  bool verifyPassword(String? password, String? salt, String? storedHash) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPassword, [password, salt, storedHash]),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i5.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setLogLevel(_i5.LogLevel? level) => super.noSuchMethod(
    Invocation.method(#setLogLevel, [level]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.LogLevel getLogLevel() =>
      (super.noSuchMethod(
            Invocation.method(#getLogLevel, []),
            returnValue: _i5.LogLevel.verbose,
          )
          as _i5.LogLevel);

  @override
  void verbose(String? message, {String? tag, dynamic data}) =>
      super.noSuchMethod(
        Invocation.method(#verbose, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void debug(String? message, {String? tag, dynamic data}) =>
      super.noSuchMethod(
        Invocation.method(#debug, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void info(String? message, {String? tag, dynamic data}) => super.noSuchMethod(
    Invocation.method(#info, [message], {#tag: tag, #data: data}),
    returnValueForMissingStub: null,
  );

  @override
  void warning(String? message, {String? tag, dynamic data}) =>
      super.noSuchMethod(
        Invocation.method(#warning, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void error(
    String? message, {
    String? tag,
    dynamic error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #error,
      [message],
      {#tag: tag, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> clearLogs() =>
      (super.noSuchMethod(
            Invocation.method(#clearLogs, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> getLogs() =>
      (super.noSuchMethod(
            Invocation.method(#getLogs, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(this, Invocation.method(#getLogs, [])),
            ),
          )
          as _i3.Future<String>);
}
