// Mocks generated by Mockito 5.4.5 from annotations
// in preparatorio_concursos/test/unit/services/share_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:firebase_performance/firebase_performance.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:preparatorio_concursos/core/data/services/interfaces/analytics_service_interface.dart'
    as _i3;
import 'package:preparatorio_concursos/core/data/services/interfaces/http_method.dart'
    as _i5;
import 'package:preparatorio_concursos/core/utils/logger.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTrace_0 extends _i1.SmartFake implements _i2.Trace {
  _FakeTrace_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpMetric_1 extends _i1.SmartFake implements _i2.HttpMetric {
  _FakeHttpMetric_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IAnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAnalyticsService extends _i1.Mock implements _i3.IAnalyticsService {
  MockIAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> logLogin({required String? method}) =>
      (super.noSuchMethod(
            Invocation.method(#logLogin, [], {#method: method}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logLogout() =>
      (super.noSuchMethod(
            Invocation.method(#logLogout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logEditalAnalysis({
    required String? editalId,
    required bool? success,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logEditalAnalysis, [], {
              #editalId: editalId,
              #success: success,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logPlanoEstudoCreation({
    required String? planoId,
    required String? editalId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logPlanoEstudoCreation, [], {
              #planoId: planoId,
              #editalId: editalId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logEstudoSession({
    required String? planoId,
    required String? materiaId,
    required String? assuntoId,
    required String? ferramenta,
    required int? duracao,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logEstudoSession, [], {
              #planoId: planoId,
              #materiaId: materiaId,
              #assuntoId: assuntoId,
              #ferramenta: ferramenta,
              #duracao: duracao,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logRecompensaPurchase({
    required String? recompensaId,
    required int? preco,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logRecompensaPurchase, [], {
              #recompensaId: recompensaId,
              #preco: preco,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logEvent({
    required String? name,
    Map<String, dynamic>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logEvent, [], {
              #name: name,
              #parameters: parameters,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> recordError(
    dynamic exception,
    StackTrace? stack, {
    String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #recordError,
              [exception, stack],
              {#reason: reason},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUser({
    required String? userId,
    String? email,
    String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setUser, [], {
              #userId: userId,
              #email: email,
              #name: name,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i2.Trace startTrace(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#startTrace, [name]),
            returnValue: _FakeTrace_0(
              this,
              Invocation.method(#startTrace, [name]),
            ),
          )
          as _i2.Trace);

  @override
  _i4.Future<void> stopTrace(_i2.Trace? trace) =>
      (super.noSuchMethod(
            Invocation.method(#stopTrace, [trace]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i2.HttpMetric startHttpMetric(String? url, _i5.AppHttpMethod? method) =>
      (super.noSuchMethod(
            Invocation.method(#startHttpMetric, [url, method]),
            returnValue: _FakeHttpMetric_1(
              this,
              Invocation.method(#startHttpMetric, [url, method]),
            ),
          )
          as _i2.HttpMetric);

  @override
  _i4.Future<void> stopHttpMetric(
    _i2.HttpMetric? metric, {
    int? responseCode,
    int? responseSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #stopHttpMetric,
              [metric],
              {#responseCode: responseCode, #responseSize: responseSize},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i6.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setLogLevel(_i6.LogLevel? level) => super.noSuchMethod(
    Invocation.method(#setLogLevel, [level]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.LogLevel getLogLevel() =>
      (super.noSuchMethod(
            Invocation.method(#getLogLevel, []),
            returnValue: _i6.LogLevel.verbose,
          )
          as _i6.LogLevel);

  @override
  void verbose(String? message, {String? tag, dynamic data}) =>
      super.noSuchMethod(
        Invocation.method(#verbose, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void debug(String? message, {String? tag, dynamic data}) =>
      super.noSuchMethod(
        Invocation.method(#debug, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void info(String? message, {String? tag, dynamic data}) => super.noSuchMethod(
    Invocation.method(#info, [message], {#tag: tag, #data: data}),
    returnValueForMissingStub: null,
  );

  @override
  void warning(String? message, {String? tag, dynamic data}) =>
      super.noSuchMethod(
        Invocation.method(#warning, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void error(
    String? message, {
    String? tag,
    dynamic error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #error,
      [message],
      {#tag: tag, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> clearLogs() =>
      (super.noSuchMethod(
            Invocation.method(#clearLogs, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> getLogs() =>
      (super.noSuchMethod(
            Invocation.method(#getLogs, []),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(this, Invocation.method(#getLogs, [])),
            ),
          )
          as _i4.Future<String>);
}
