// Mocks generated by Mockito 5.4.5 from annotations
// in preparatorio_concursos/test/widget/api_key_config_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:preparatorio_concursos/core/data/services/ia_service.dart'
    as _i4;
import 'package:preparatorio_concursos/core/services/api_config_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ApiConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiConfigService extends _i1.Mock implements _i2.ApiConfigService {
  MockApiConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConfigured =>
      (super.noSuchMethod(Invocation.getter(#isConfigured), returnValue: false)
          as bool);

  @override
  bool get isValidated =>
      (super.noSuchMethod(Invocation.getter(#isValidated), returnValue: false)
          as bool);

  @override
  String get apiModel =>
      (super.noSuchMethod(
            Invocation.getter(#apiModel),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#apiModel),
            ),
          )
          as String);

  @override
  bool get isVerifyingConfig =>
      (super.noSuchMethod(
            Invocation.getter(#isVerifyingConfig),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setIAService(_i4.IAService? iaService) => super.noSuchMethod(
    Invocation.method(#setIAService, [iaService]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> setLlmConfigured(bool? isConfigured) =>
      (super.noSuchMethod(
            Invocation.method(#setLlmConfigured, [isConfigured]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> isApiConfigured() =>
      (super.noSuchMethod(
            Invocation.method(#isApiConfigured, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> saveApiKey(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#saveApiKey, [apiKey]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearApiKey() =>
      (super.noSuchMethod(
            Invocation.method(#clearApiKey, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> isApiKeyValid(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#isApiKeyValid, [apiKey]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> setApiModel(String? model) =>
      (super.noSuchMethod(
            Invocation.method(#setApiModel, [model]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> verificarConfiguracao() =>
      (super.noSuchMethod(
            Invocation.method(#verificarConfiguracao, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
