// Mocks generated by Mockito 5.4.5 from annotations
// in preparatorio_concursos/test/widget/cargo_select_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:preparatorio_concursos/core/data/models/edital.dart' as _i2;
import 'package:preparatorio_concursos/core/data/services/edital_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEdital_0 extends _i1.SmartFake implements _i2.Edital {
  _FakeEdital_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDadosExtraidos_1 extends _i1.SmartFake
    implements _i2.DadosExtraidos {
  _FakeDadosExtraidos_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EditalService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditalService extends _i1.Mock implements _i3.EditalService {
  MockEditalService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Edital> get editais =>
      (super.noSuchMethod(
            Invocation.getter(#editais),
            returnValue: <_i2.Edital>[],
          )
          as List<_i2.Edital>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> loadEditais() =>
      (super.noSuchMethod(
            Invocation.method(#loadEditais, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Edital> addEdital(
    String? userId,
    String? nomeConcurso,
    String? textoCompleto,
    _i2.DadosExtraidos? dadosExtraidos, {
    Map<String, dynamic>? dadosOriginais,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addEdital,
              [userId, nomeConcurso, textoCompleto, dadosExtraidos],
              {#dadosOriginais: dadosOriginais},
            ),
            returnValue: _i4.Future<_i2.Edital>.value(
              _FakeEdital_0(
                this,
                Invocation.method(
                  #addEdital,
                  [userId, nomeConcurso, textoCompleto, dadosExtraidos],
                  {#dadosOriginais: dadosOriginais},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Edital>);

  @override
  _i2.Edital? getEditalById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getEditalById, [id]))
          as _i2.Edital?);

  @override
  List<_i2.Edital> getEditaisByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getEditaisByUserId, [userId]),
            returnValue: <_i2.Edital>[],
          )
          as List<_i2.Edital>);

  @override
  _i4.Future<bool> updateEdital(_i2.Edital? editalAtualizado) =>
      (super.noSuchMethod(
            Invocation.method(#updateEdital, [editalAtualizado]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> removeEdital(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeEdital, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> atualizarConteudoProgramaticoCargo(
    String? editalId,
    String? cargoNome,
    Map<String, dynamic>? conteudoProgramatico,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#atualizarConteudoProgramaticoCargo, [
              editalId,
              cargoNome,
              conteudoProgramatico,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.DadosExtraidos> extrairDadosEdital(String? textoEdital) =>
      (super.noSuchMethod(
            Invocation.method(#extrairDadosEdital, [textoEdital]),
            returnValue: _i4.Future<_i2.DadosExtraidos>.value(
              _FakeDadosExtraidos_1(
                this,
                Invocation.method(#extrairDadosEdital, [textoEdital]),
              ),
            ),
          )
          as _i4.Future<_i2.DadosExtraidos>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
