// Mocks generated by Mockito 5.4.5 from annotations
// in preparatorio_concursos/test/widget/edital_analyze_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i9;
import 'dart:ui' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:preparatorio_concursos/core/data/models/edital.dart' as _i2;
import 'package:preparatorio_concursos/core/data/models/flashcard.dart' as _i8;
import 'package:preparatorio_concursos/core/data/services/edital_service.dart'
    as _i3;
import 'package:preparatorio_concursos/core/data/services/ia_service.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEdital_0 extends _i1.SmartFake implements _i2.Edital {
  _FakeEdital_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDadosExtraidos_1 extends _i1.SmartFake
    implements _i2.DadosExtraidos {
  _FakeDadosExtraidos_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EditalService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditalService extends _i1.Mock implements _i3.EditalService {
  MockEditalService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Edital> get editais =>
      (super.noSuchMethod(
            Invocation.getter(#editais),
            returnValue: <_i2.Edital>[],
          )
          as List<_i2.Edital>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> loadEditais() =>
      (super.noSuchMethod(
            Invocation.method(#loadEditais, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Edital> addEdital(
    String? userId,
    String? nomeConcurso,
    String? textoCompleto,
    _i2.DadosExtraidos? dadosExtraidos, {
    Map<String, dynamic>? dadosOriginais,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addEdital,
              [userId, nomeConcurso, textoCompleto, dadosExtraidos],
              {#dadosOriginais: dadosOriginais},
            ),
            returnValue: _i4.Future<_i2.Edital>.value(
              _FakeEdital_0(
                this,
                Invocation.method(
                  #addEdital,
                  [userId, nomeConcurso, textoCompleto, dadosExtraidos],
                  {#dadosOriginais: dadosOriginais},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Edital>);

  @override
  _i2.Edital? getEditalById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getEditalById, [id]))
          as _i2.Edital?);

  @override
  List<_i2.Edital> getEditaisByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getEditaisByUserId, [userId]),
            returnValue: <_i2.Edital>[],
          )
          as List<_i2.Edital>);

  @override
  _i4.Future<bool> updateEdital(_i2.Edital? editalAtualizado) =>
      (super.noSuchMethod(
            Invocation.method(#updateEdital, [editalAtualizado]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> removeEdital(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeEdital, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> atualizarConteudoProgramaticoCargo(
    String? editalId,
    String? cargoNome,
    Map<String, dynamic>? conteudoProgramatico,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#atualizarConteudoProgramaticoCargo, [
              editalId,
              cargoNome,
              conteudoProgramatico,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.DadosExtraidos> extrairDadosEdital(String? textoEdital) =>
      (super.noSuchMethod(
            Invocation.method(#extrairDadosEdital, [textoEdital]),
            returnValue: _i4.Future<_i2.DadosExtraidos>.value(
              _FakeDadosExtraidos_1(
                this,
                Invocation.method(#extrairDadosEdital, [textoEdital]),
              ),
            ),
          )
          as _i4.Future<_i2.DadosExtraidos>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [IAService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAService extends _i1.Mock implements _i6.IAService {
  MockIAService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConfigured =>
      (super.noSuchMethod(Invocation.getter(#isConfigured), returnValue: false)
          as bool);

  @override
  String get apiType =>
      (super.noSuchMethod(
            Invocation.getter(#apiType),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#apiType),
            ),
          )
          as String);

  @override
  bool get forceCacheMode =>
      (super.noSuchMethod(
            Invocation.getter(#forceCacheMode),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void switchService(String? apiType) => super.noSuchMethod(
    Invocation.method(#switchService, [apiType]),
    returnValueForMissingStub: null,
  );

  @override
  void setApiType(String? apiType) => super.noSuchMethod(
    Invocation.method(#setApiType, [apiType]),
    returnValueForMissingStub: null,
  );

  @override
  void setForceCacheMode(bool? value) => super.noSuchMethod(
    Invocation.method(#setForceCacheMode, [value]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> initCache() =>
      (super.noSuchMethod(
            Invocation.method(#initCache, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>> setApiKey(String? apiKey, String? apiType) =>
      (super.noSuchMethod(
            Invocation.method(#setApiKey, [apiKey, apiType]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  bool isWithinTokenLimit(String? texto) =>
      (super.noSuchMethod(
            Invocation.method(#isWithinTokenLimit, [texto]),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<bool> configurarApiKey(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#configurarApiKey, [apiKey]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> testApiKey(String? apiKey, String? apiType) =>
      (super.noSuchMethod(
            Invocation.method(#testApiKey, [apiKey, apiType]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String> callApiWithPrompt(String? prompt) =>
      (super.noSuchMethod(
            Invocation.method(#callApiWithPrompt, [prompt]),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#callApiWithPrompt, [prompt]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  dynamic parseJsonResponse(String? jsonString) =>
      super.noSuchMethod(Invocation.method(#parseJsonResponse, [jsonString]));

  @override
  _i4.Future<Map<String, dynamic>?> gerarRespostaJson(String? prompt) =>
      (super.noSuchMethod(
            Invocation.method(#gerarRespostaJson, [prompt]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<List<_i8.Flashcard>> gerarFlashcards({
    required String? userId,
    String? editalId,
    required String? materia,
    required String? texto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#gerarFlashcards, [], {
              #userId: userId,
              #editalId: editalId,
              #materia: materia,
              #texto: texto,
            }),
            returnValue: _i4.Future<List<_i8.Flashcard>>.value(
              <_i8.Flashcard>[],
            ),
          )
          as _i4.Future<List<_i8.Flashcard>>);

  @override
  _i4.Future<String> analisarEditalPdf(
    _i9.Uint8List? pdfBytes, {
    String? pdfName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #analisarEditalPdf,
              [pdfBytes],
              {#pdfName: pdfName},
            ),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #analisarEditalPdf,
                  [pdfBytes],
                  {#pdfName: pdfName},
                ),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> extrairCargosEdital(
    _i9.Uint8List? pdfBytes, {
    String? pdfName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #extrairCargosEdital,
              [pdfBytes],
              {#pdfName: pdfName},
            ),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #extrairCargosEdital,
                  [pdfBytes],
                  {#pdfName: pdfName},
                ),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> extrairInfoBasicasEdital(
    _i9.Uint8List? pdfBytes, {
    String? pdfName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #extrairInfoBasicasEdital,
              [pdfBytes],
              {#pdfName: pdfName},
            ),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #extrairInfoBasicasEdital,
                  [pdfBytes],
                  {#pdfName: pdfName},
                ),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> extrairConcursoConteudo({
    required _i9.Uint8List? pdfBytes,
    required String? cargoAlvo,
    String? pdfName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#extrairConcursoConteudo, [], {
              #pdfBytes: pdfBytes,
              #cargoAlvo: cargoAlvo,
              #pdfName: pdfName,
            }),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#extrairConcursoConteudo, [], {
                  #pdfBytes: pdfBytes,
                  #cargoAlvo: cargoAlvo,
                  #pdfName: pdfName,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> extrairConteudoProgramatico({
    required _i9.Uint8List? pdfBytes,
    required String? cargoAlvo,
    String? pdfName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#extrairConteudoProgramatico, [], {
              #pdfBytes: pdfBytes,
              #cargoAlvo: cargoAlvo,
              #pdfName: pdfName,
            }),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#extrairConteudoProgramatico, [], {
                  #pdfBytes: pdfBytes,
                  #cargoAlvo: cargoAlvo,
                  #pdfName: pdfName,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> gerarResumo(String? texto) =>
      (super.noSuchMethod(
            Invocation.method(#gerarResumo, [texto]),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#gerarResumo, [texto]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> gerarEsquema({required String? texto, String? titulo}) =>
      (super.noSuchMethod(
            Invocation.method(#gerarEsquema, [], {
              #texto: texto,
              #titulo: titulo,
            }),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#gerarEsquema, [], {
                  #texto: texto,
                  #titulo: titulo,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> gerarQuestoes({
    required String? texto,
    required String? materia,
    required String? dificuldade,
    required int? quantidade,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#gerarQuestoes, [], {
              #texto: texto,
              #materia: materia,
              #dificuldade: dificuldade,
              #quantidade: quantidade,
            }),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#gerarQuestoes, [], {
                  #texto: texto,
                  #materia: materia,
                  #dificuldade: dificuldade,
                  #quantidade: quantidade,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> callApi(String? prompt) =>
      (super.noSuchMethod(
            Invocation.method(#callApi, [prompt]),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#callApi, [prompt]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> callGeminiApiWithPdf(
    String? prompt,
    _i9.Uint8List? pdfBytes, {
    String? pdfName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #callGeminiApiWithPdf,
              [prompt, pdfBytes],
              {#pdfName: pdfName},
            ),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #callGeminiApiWithPdf,
                  [prompt, pdfBytes],
                  {#pdfName: pdfName},
                ),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
