// Mocks generated by Mockito 5.4.5 from annotations
// in preparatorio_concursos/test/widget/plano_resumo_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:preparatorio_concursos/core/data/models/assunto.dart' as _i4;
import 'package:preparatorio_concursos/core/data/models/materia.dart' as _i3;
import 'package:preparatorio_concursos/core/data/models/models.dart' as _i2;
import 'package:preparatorio_concursos/core/data/services/edital_service.dart'
    as _i8;
import 'package:preparatorio_concursos/core/data/services/plano_estudo_service.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePlanoEstudo_0 extends _i1.SmartFake implements _i2.PlanoEstudo {
  _FakePlanoEstudo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMateria_1 extends _i1.SmartFake implements _i3.Materia {
  _FakeMateria_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAssunto_2 extends _i1.SmartFake implements _i4.Assunto {
  _FakeAssunto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEdital_3 extends _i1.SmartFake implements _i2.Edital {
  _FakeEdital_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDadosExtraidos_4 extends _i1.SmartFake
    implements _i2.DadosExtraidos {
  _FakeDadosExtraidos_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PlanoEstudoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlanoEstudoService extends _i1.Mock
    implements _i5.PlanoEstudoService {
  MockPlanoEstudoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.PlanoEstudo> get planos =>
      (super.noSuchMethod(
            Invocation.getter(#planos),
            returnValue: <_i2.PlanoEstudo>[],
          )
          as List<_i2.PlanoEstudo>);

  @override
  List<_i2.CronogramaItem> get cronogramaItems =>
      (super.noSuchMethod(
            Invocation.getter(#cronogramaItems),
            returnValue: <_i2.CronogramaItem>[],
          )
          as List<_i2.CronogramaItem>);

  @override
  List<_i3.Materia> get materias =>
      (super.noSuchMethod(
            Invocation.getter(#materias),
            returnValue: <_i3.Materia>[],
          )
          as List<_i3.Materia>);

  @override
  List<_i4.Assunto> get assuntos =>
      (super.noSuchMethod(
            Invocation.getter(#assuntos),
            returnValue: <_i4.Assunto>[],
          )
          as List<_i4.Assunto>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> loadPlanos() =>
      (super.noSuchMethod(
            Invocation.method(#loadPlanos, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.PlanoEstudo> criarPlanoEstudo(
    String? userId,
    String? editalId,
    List<String>? cargoIds,
    DateTime? dataInicio,
    DateTime? dataFim,
    Map<String, int>? horasSemanais,
    List<String>? ferramentas,
    List<_i2.MateriaProficiencia>? materiasProficiencia,
    List<_i2.RecompensaConfig>? recompensas, {
    Map<String, List<int>>? horariosEspecificos,
    Map<String, dynamic>? dadosAdicionais,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #criarPlanoEstudo,
              [
                userId,
                editalId,
                cargoIds,
                dataInicio,
                dataFim,
                horasSemanais,
                ferramentas,
                materiasProficiencia,
                recompensas,
              ],
              {
                #horariosEspecificos: horariosEspecificos,
                #dadosAdicionais: dadosAdicionais,
              },
            ),
            returnValue: _i6.Future<_i2.PlanoEstudo>.value(
              _FakePlanoEstudo_0(
                this,
                Invocation.method(
                  #criarPlanoEstudo,
                  [
                    userId,
                    editalId,
                    cargoIds,
                    dataInicio,
                    dataFim,
                    horasSemanais,
                    ferramentas,
                    materiasProficiencia,
                    recompensas,
                  ],
                  {
                    #horariosEspecificos: horariosEspecificos,
                    #dadosAdicionais: dadosAdicionais,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.PlanoEstudo>);

  @override
  _i2.PlanoEstudo? getPlanoById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getPlanoById, [id]))
          as _i2.PlanoEstudo?);

  @override
  List<_i2.PlanoEstudo> getPlanosByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanosByUserId, [userId]),
            returnValue: <_i2.PlanoEstudo>[],
          )
          as List<_i2.PlanoEstudo>);

  @override
  List<_i2.CronogramaItem> getCronogramaByPlanoId(String? planoId) =>
      (super.noSuchMethod(
            Invocation.method(#getCronogramaByPlanoId, [planoId]),
            returnValue: <_i2.CronogramaItem>[],
          )
          as List<_i2.CronogramaItem>);

  @override
  List<_i2.CronogramaItem> getCronogramaByDate(DateTime? data) =>
      (super.noSuchMethod(
            Invocation.method(#getCronogramaByDate, [data]),
            returnValue: <_i2.CronogramaItem>[],
          )
          as List<_i2.CronogramaItem>);

  @override
  _i6.Future<bool> updateCronogramaItemStatus(
    String? itemId,
    _i2.StatusItem? novoStatus,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCronogramaItemStatus, [
              itemId,
              novoStatus,
            ]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> removePlano(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removePlano, [id]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i3.Materia> addMateria(
    String? nome,
    String? editalId,
    String? cargoId,
    int? nivelProficiencia,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addMateria, [
              nome,
              editalId,
              cargoId,
              nivelProficiencia,
            ]),
            returnValue: _i6.Future<_i3.Materia>.value(
              _FakeMateria_1(
                this,
                Invocation.method(#addMateria, [
                  nome,
                  editalId,
                  cargoId,
                  nivelProficiencia,
                ]),
              ),
            ),
          )
          as _i6.Future<_i3.Materia>);

  @override
  List<_i3.Materia> getMateriasByEditalAndCargo(
    String? editalId,
    String? cargoId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMateriasByEditalAndCargo, [
              editalId,
              cargoId,
            ]),
            returnValue: <_i3.Materia>[],
          )
          as List<_i3.Materia>);

  @override
  _i3.Materia? getMateriaById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getMateriaById, [id]))
          as _i3.Materia?);

  @override
  _i6.Future<bool> updateMateria(_i3.Materia? materia) =>
      (super.noSuchMethod(
            Invocation.method(#updateMateria, [materia]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> removeMateria(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeMateria, [id]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i4.Assunto> addAssunto(
    String? nome,
    String? materiaId,
    int? ordem,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addAssunto, [nome, materiaId, ordem]),
            returnValue: _i6.Future<_i4.Assunto>.value(
              _FakeAssunto_2(
                this,
                Invocation.method(#addAssunto, [nome, materiaId, ordem]),
              ),
            ),
          )
          as _i6.Future<_i4.Assunto>);

  @override
  List<_i4.Assunto> getAssuntosByMateria(String? materiaId) =>
      (super.noSuchMethod(
            Invocation.method(#getAssuntosByMateria, [materiaId]),
            returnValue: <_i4.Assunto>[],
          )
          as List<_i4.Assunto>);

  @override
  _i4.Assunto? getAssuntoById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getAssuntoById, [id]))
          as _i4.Assunto?);

  @override
  _i6.Future<bool> updateAssunto(_i4.Assunto? assunto) =>
      (super.noSuchMethod(
            Invocation.method(#updateAssunto, [assunto]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> marcarAssuntoComoEstudado(String? id, bool? isEstudado) =>
      (super.noSuchMethod(
            Invocation.method(#marcarAssuntoComoEstudado, [id, isEstudado]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> removeAssunto(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeAssunto, [id]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [EditalService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditalService extends _i1.Mock implements _i8.EditalService {
  MockEditalService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Edital> get editais =>
      (super.noSuchMethod(
            Invocation.getter(#editais),
            returnValue: <_i2.Edital>[],
          )
          as List<_i2.Edital>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> loadEditais() =>
      (super.noSuchMethod(
            Invocation.method(#loadEditais, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.Edital> addEdital(
    String? userId,
    String? nomeConcurso,
    String? textoCompleto,
    _i2.DadosExtraidos? dadosExtraidos, {
    Map<String, dynamic>? dadosOriginais,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addEdital,
              [userId, nomeConcurso, textoCompleto, dadosExtraidos],
              {#dadosOriginais: dadosOriginais},
            ),
            returnValue: _i6.Future<_i2.Edital>.value(
              _FakeEdital_3(
                this,
                Invocation.method(
                  #addEdital,
                  [userId, nomeConcurso, textoCompleto, dadosExtraidos],
                  {#dadosOriginais: dadosOriginais},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Edital>);

  @override
  _i2.Edital? getEditalById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getEditalById, [id]))
          as _i2.Edital?);

  @override
  List<_i2.Edital> getEditaisByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getEditaisByUserId, [userId]),
            returnValue: <_i2.Edital>[],
          )
          as List<_i2.Edital>);

  @override
  _i6.Future<bool> updateEdital(_i2.Edital? editalAtualizado) =>
      (super.noSuchMethod(
            Invocation.method(#updateEdital, [editalAtualizado]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> removeEdital(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeEdital, [id]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> atualizarConteudoProgramaticoCargo(
    String? editalId,
    String? cargoNome,
    Map<String, dynamic>? conteudoProgramatico,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#atualizarConteudoProgramaticoCargo, [
              editalId,
              cargoNome,
              conteudoProgramatico,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.DadosExtraidos> extrairDadosEdital(String? textoEdital) =>
      (super.noSuchMethod(
            Invocation.method(#extrairDadosEdital, [textoEdital]),
            returnValue: _i6.Future<_i2.DadosExtraidos>.value(
              _FakeDadosExtraidos_4(
                this,
                Invocation.method(#extrairDadosEdital, [textoEdital]),
              ),
            ),
          )
          as _i6.Future<_i2.DadosExtraidos>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
