// Mocks generated by Mockito 5.4.5 from annotations
// in preparatorio_concursos/test/features/2_edital/edital_analysis_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i7;
import 'dart:ui' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:preparatorio_concursos/core/data/models/flashcard.dart' as _i6;
import 'package:preparatorio_concursos/core/data/services/ia_service.dart'
    as _i3;
import 'package:preparatorio_concursos/core/utils/pdf_processor.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePdfProcessorConfig_0 extends _i1.SmartFake
    implements _i2.PdfProcessorConfig {
  _FakePdfProcessorConfig_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePdfProcessingResult_1 extends _i1.SmartFake
    implements _i2.PdfProcessingResult {
  _FakePdfProcessingResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IAService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAService extends _i1.Mock implements _i3.IAService {
  MockIAService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConfigured =>
      (super.noSuchMethod(Invocation.getter(#isConfigured), returnValue: false)
          as bool);

  @override
  String get apiType =>
      (super.noSuchMethod(
            Invocation.getter(#apiType),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#apiType),
            ),
          )
          as String);

  @override
  bool get forceCacheMode =>
      (super.noSuchMethod(
            Invocation.getter(#forceCacheMode),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void switchService(String? apiType) => super.noSuchMethod(
    Invocation.method(#switchService, [apiType]),
    returnValueForMissingStub: null,
  );

  @override
  void setApiType(String? apiType) => super.noSuchMethod(
    Invocation.method(#setApiType, [apiType]),
    returnValueForMissingStub: null,
  );

  @override
  void setForceCacheMode(bool? value) => super.noSuchMethod(
    Invocation.method(#setForceCacheMode, [value]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> initCache() =>
      (super.noSuchMethod(
            Invocation.method(#initCache, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<Map<String, dynamic>> setApiKey(String? apiKey, String? apiType) =>
      (super.noSuchMethod(
            Invocation.method(#setApiKey, [apiKey, apiType]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  bool isWithinTokenLimit(String? texto) =>
      (super.noSuchMethod(
            Invocation.method(#isWithinTokenLimit, [texto]),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<bool> configurarApiKey(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#configurarApiKey, [apiKey]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> testApiKey(String? apiKey, String? apiType) =>
      (super.noSuchMethod(
            Invocation.method(#testApiKey, [apiKey, apiType]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<String> callApiWithPrompt(String? prompt) =>
      (super.noSuchMethod(
            Invocation.method(#callApiWithPrompt, [prompt]),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#callApiWithPrompt, [prompt]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  dynamic parseJsonResponse(String? jsonString) =>
      super.noSuchMethod(Invocation.method(#parseJsonResponse, [jsonString]));

  @override
  _i5.Future<Map<String, dynamic>?> gerarRespostaJson(String? prompt) =>
      (super.noSuchMethod(
            Invocation.method(#gerarRespostaJson, [prompt]),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<List<_i6.Flashcard>> gerarFlashcards({
    required String? userId,
    String? editalId,
    required String? materia,
    required String? texto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#gerarFlashcards, [], {
              #userId: userId,
              #editalId: editalId,
              #materia: materia,
              #texto: texto,
            }),
            returnValue: _i5.Future<List<_i6.Flashcard>>.value(
              <_i6.Flashcard>[],
            ),
          )
          as _i5.Future<List<_i6.Flashcard>>);

  @override
  _i5.Future<String> analisarEditalPdf(
    _i7.Uint8List? pdfBytes, {
    String? pdfName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #analisarEditalPdf,
              [pdfBytes],
              {#pdfName: pdfName},
            ),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(
                  #analisarEditalPdf,
                  [pdfBytes],
                  {#pdfName: pdfName},
                ),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> extrairCargosEdital(
    _i7.Uint8List? pdfBytes, {
    String? pdfName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #extrairCargosEdital,
              [pdfBytes],
              {#pdfName: pdfName},
            ),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(
                  #extrairCargosEdital,
                  [pdfBytes],
                  {#pdfName: pdfName},
                ),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> extrairInfoBasicasEdital(
    _i7.Uint8List? pdfBytes, {
    String? pdfName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #extrairInfoBasicasEdital,
              [pdfBytes],
              {#pdfName: pdfName},
            ),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(
                  #extrairInfoBasicasEdital,
                  [pdfBytes],
                  {#pdfName: pdfName},
                ),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> extrairConcursoConteudo({
    required _i7.Uint8List? pdfBytes,
    required String? cargoAlvo,
    String? pdfName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#extrairConcursoConteudo, [], {
              #pdfBytes: pdfBytes,
              #cargoAlvo: cargoAlvo,
              #pdfName: pdfName,
            }),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#extrairConcursoConteudo, [], {
                  #pdfBytes: pdfBytes,
                  #cargoAlvo: cargoAlvo,
                  #pdfName: pdfName,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> extrairConteudoProgramatico({
    required _i7.Uint8List? pdfBytes,
    required String? cargoAlvo,
    String? pdfName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#extrairConteudoProgramatico, [], {
              #pdfBytes: pdfBytes,
              #cargoAlvo: cargoAlvo,
              #pdfName: pdfName,
            }),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#extrairConteudoProgramatico, [], {
                  #pdfBytes: pdfBytes,
                  #cargoAlvo: cargoAlvo,
                  #pdfName: pdfName,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> gerarResumo(String? texto) =>
      (super.noSuchMethod(
            Invocation.method(#gerarResumo, [texto]),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#gerarResumo, [texto]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> gerarEsquema({required String? texto, String? titulo}) =>
      (super.noSuchMethod(
            Invocation.method(#gerarEsquema, [], {
              #texto: texto,
              #titulo: titulo,
            }),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#gerarEsquema, [], {
                  #texto: texto,
                  #titulo: titulo,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> gerarQuestoes({
    required String? texto,
    required String? materia,
    required String? dificuldade,
    required int? quantidade,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#gerarQuestoes, [], {
              #texto: texto,
              #materia: materia,
              #dificuldade: dificuldade,
              #quantidade: quantidade,
            }),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#gerarQuestoes, [], {
                  #texto: texto,
                  #materia: materia,
                  #dificuldade: dificuldade,
                  #quantidade: quantidade,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> callApi(String? prompt) =>
      (super.noSuchMethod(
            Invocation.method(#callApi, [prompt]),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#callApi, [prompt]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> callGeminiApiWithPdf(
    String? prompt,
    _i7.Uint8List? pdfBytes, {
    String? pdfName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #callGeminiApiWithPdf,
              [prompt, pdfBytes],
              {#pdfName: pdfName},
            ),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(
                  #callGeminiApiWithPdf,
                  [prompt, pdfBytes],
                  {#pdfName: pdfName},
                ),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PdfProcessor].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfProcessor extends _i1.Mock implements _i2.PdfProcessor {
  MockPdfProcessor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PdfProcessorConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakePdfProcessorConfig_0(
              this,
              Invocation.getter(#config),
            ),
          )
          as _i2.PdfProcessorConfig);

  @override
  _i5.Future<_i2.PdfProcessingResult> extractTextFromPdf(
    dynamic pdfSource, {
    bool? useOcr,
    bool? useAdvancedMethods,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #extractTextFromPdf,
              [pdfSource],
              {#useOcr: useOcr, #useAdvancedMethods: useAdvancedMethods},
            ),
            returnValue: _i5.Future<_i2.PdfProcessingResult>.value(
              _FakePdfProcessingResult_1(
                this,
                Invocation.method(
                  #extractTextFromPdf,
                  [pdfSource],
                  {#useOcr: useOcr, #useAdvancedMethods: useAdvancedMethods},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.PdfProcessingResult>);

  @override
  _i5.Future<_i2.PdfProcessingResult> extractTextFromPdfBytes(
    _i7.Uint8List? bytes, {
    bool? useOcr,
    bool? useAdvancedMethods,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #extractTextFromPdfBytes,
              [bytes],
              {#useOcr: useOcr, #useAdvancedMethods: useAdvancedMethods},
            ),
            returnValue: _i5.Future<_i2.PdfProcessingResult>.value(
              _FakePdfProcessingResult_1(
                this,
                Invocation.method(
                  #extractTextFromPdfBytes,
                  [bytes],
                  {#useOcr: useOcr, #useAdvancedMethods: useAdvancedMethods},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.PdfProcessingResult>);

  @override
  _i5.Future<bool> isPdfScanned(_i7.Uint8List? pdfBytes) =>
      (super.noSuchMethod(
            Invocation.method(#isPdfScanned, [pdfBytes]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<String> processLargePdf(
    _i7.Uint8List? pdfBytes, {
    int? chunkSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #processLargePdf,
              [pdfBytes],
              {#chunkSize: chunkSize},
            ),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(
                  #processLargePdf,
                  [pdfBytes],
                  {#chunkSize: chunkSize},
                ),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<Map<String, String>> processBatchPdfs(
    List<_i7.Uint8List>? pdfBytesList,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#processBatchPdfs, [pdfBytesList]),
            returnValue: _i5.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i5.Future<Map<String, String>>);
}
