// Mocks generated by Mockito 5.4.5 from annotations
// in preparatorio_concursos/test/integration/plano_estudo_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:typed_data' as _i13;
import 'dart:ui' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:preparatorio_concursos/core/auth/auth_service.dart' as _i6;
import 'package:preparatorio_concursos/core/data/models/assunto.dart' as _i5;
import 'package:preparatorio_concursos/core/data/models/edital.dart' as _i2;
import 'package:preparatorio_concursos/core/data/models/materia.dart' as _i4;
import 'package:preparatorio_concursos/core/data/models/models.dart' as _i3;
import 'package:preparatorio_concursos/core/data/services/edital_service.dart'
    as _i10;
import 'package:preparatorio_concursos/core/data/services/ia_service.dart'
    as _i12;
import 'package:preparatorio_concursos/core/data/services/plano_estudo_service.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEdital_0 extends _i1.SmartFake implements _i2.Edital {
  _FakeEdital_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDadosExtraidos_1 extends _i1.SmartFake
    implements _i2.DadosExtraidos {
  _FakeDadosExtraidos_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlanoEstudo_2 extends _i1.SmartFake implements _i3.PlanoEstudo {
  _FakePlanoEstudo_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMateria_3 extends _i1.SmartFake implements _i4.Materia {
  _FakeMateria_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAssunto_4 extends _i1.SmartFake implements _i5.Assunto {
  _FakeAssunto_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i6.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  String get assinaturaAtual =>
      (super.noSuchMethod(
            Invocation.getter(#assinaturaAtual),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#assinaturaAtual),
            ),
          )
          as String);

  @override
  bool get isPremium =>
      (super.noSuchMethod(Invocation.getter(#isPremium), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i8.Future<bool> checkAuthStatus() =>
      (super.noSuchMethod(
            Invocation.method(#checkAuthStatus, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> register(
    String? nome,
    String? email,
    String? password, {
    bool? isPremium = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #register,
              [nome, email, password],
              {#isPremium: isPremium},
            ),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> upgradeToPremium() =>
      (super.noSuchMethod(
            Invocation.method(#upgradeToPremium, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  bool isPremiumFeatureAvailable(String? feature) =>
      (super.noSuchMethod(
            Invocation.method(#isPremiumFeatureAvailable, [feature]),
            returnValue: false,
          )
          as bool);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [EditalService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditalService extends _i1.Mock implements _i10.EditalService {
  MockEditalService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Edital> get editais =>
      (super.noSuchMethod(
            Invocation.getter(#editais),
            returnValue: <_i2.Edital>[],
          )
          as List<_i2.Edital>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i8.Future<void> loadEditais() =>
      (super.noSuchMethod(
            Invocation.method(#loadEditais, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i2.Edital> addEdital(
    String? userId,
    String? nomeConcurso,
    String? textoCompleto,
    _i2.DadosExtraidos? dadosExtraidos, {
    Map<String, dynamic>? dadosOriginais,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addEdital,
              [userId, nomeConcurso, textoCompleto, dadosExtraidos],
              {#dadosOriginais: dadosOriginais},
            ),
            returnValue: _i8.Future<_i2.Edital>.value(
              _FakeEdital_0(
                this,
                Invocation.method(
                  #addEdital,
                  [userId, nomeConcurso, textoCompleto, dadosExtraidos],
                  {#dadosOriginais: dadosOriginais},
                ),
              ),
            ),
          )
          as _i8.Future<_i2.Edital>);

  @override
  _i2.Edital? getEditalById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getEditalById, [id]))
          as _i2.Edital?);

  @override
  List<_i2.Edital> getEditaisByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getEditaisByUserId, [userId]),
            returnValue: <_i2.Edital>[],
          )
          as List<_i2.Edital>);

  @override
  _i8.Future<bool> updateEdital(_i2.Edital? editalAtualizado) =>
      (super.noSuchMethod(
            Invocation.method(#updateEdital, [editalAtualizado]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> removeEdital(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeEdital, [id]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> atualizarConteudoProgramaticoCargo(
    String? editalId,
    String? cargoNome,
    Map<String, dynamic>? conteudoProgramatico,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#atualizarConteudoProgramaticoCargo, [
              editalId,
              cargoNome,
              conteudoProgramatico,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i2.DadosExtraidos> extrairDadosEdital(String? textoEdital) =>
      (super.noSuchMethod(
            Invocation.method(#extrairDadosEdital, [textoEdital]),
            returnValue: _i8.Future<_i2.DadosExtraidos>.value(
              _FakeDadosExtraidos_1(
                this,
                Invocation.method(#extrairDadosEdital, [textoEdital]),
              ),
            ),
          )
          as _i8.Future<_i2.DadosExtraidos>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PlanoEstudoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlanoEstudoService extends _i1.Mock
    implements _i11.PlanoEstudoService {
  MockPlanoEstudoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.PlanoEstudo> get planos =>
      (super.noSuchMethod(
            Invocation.getter(#planos),
            returnValue: <_i3.PlanoEstudo>[],
          )
          as List<_i3.PlanoEstudo>);

  @override
  List<_i3.CronogramaItem> get cronogramaItems =>
      (super.noSuchMethod(
            Invocation.getter(#cronogramaItems),
            returnValue: <_i3.CronogramaItem>[],
          )
          as List<_i3.CronogramaItem>);

  @override
  List<_i4.Materia> get materias =>
      (super.noSuchMethod(
            Invocation.getter(#materias),
            returnValue: <_i4.Materia>[],
          )
          as List<_i4.Materia>);

  @override
  List<_i5.Assunto> get assuntos =>
      (super.noSuchMethod(
            Invocation.getter(#assuntos),
            returnValue: <_i5.Assunto>[],
          )
          as List<_i5.Assunto>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i8.Future<void> loadPlanos() =>
      (super.noSuchMethod(
            Invocation.method(#loadPlanos, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i3.PlanoEstudo> criarPlanoEstudo(
    String? userId,
    String? editalId,
    List<String>? cargoIds,
    DateTime? dataInicio,
    DateTime? dataFim,
    Map<String, int>? horasSemanais,
    List<String>? ferramentas,
    List<_i3.MateriaProficiencia>? materiasProficiencia,
    List<_i3.RecompensaConfig>? recompensas, {
    Map<String, List<int>>? horariosEspecificos,
    Map<String, dynamic>? dadosAdicionais,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #criarPlanoEstudo,
              [
                userId,
                editalId,
                cargoIds,
                dataInicio,
                dataFim,
                horasSemanais,
                ferramentas,
                materiasProficiencia,
                recompensas,
              ],
              {
                #horariosEspecificos: horariosEspecificos,
                #dadosAdicionais: dadosAdicionais,
              },
            ),
            returnValue: _i8.Future<_i3.PlanoEstudo>.value(
              _FakePlanoEstudo_2(
                this,
                Invocation.method(
                  #criarPlanoEstudo,
                  [
                    userId,
                    editalId,
                    cargoIds,
                    dataInicio,
                    dataFim,
                    horasSemanais,
                    ferramentas,
                    materiasProficiencia,
                    recompensas,
                  ],
                  {
                    #horariosEspecificos: horariosEspecificos,
                    #dadosAdicionais: dadosAdicionais,
                  },
                ),
              ),
            ),
          )
          as _i8.Future<_i3.PlanoEstudo>);

  @override
  _i3.PlanoEstudo? getPlanoById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getPlanoById, [id]))
          as _i3.PlanoEstudo?);

  @override
  List<_i3.PlanoEstudo> getPlanosByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanosByUserId, [userId]),
            returnValue: <_i3.PlanoEstudo>[],
          )
          as List<_i3.PlanoEstudo>);

  @override
  List<_i3.CronogramaItem> getCronogramaByPlanoId(String? planoId) =>
      (super.noSuchMethod(
            Invocation.method(#getCronogramaByPlanoId, [planoId]),
            returnValue: <_i3.CronogramaItem>[],
          )
          as List<_i3.CronogramaItem>);

  @override
  List<_i3.CronogramaItem> getCronogramaByDate(DateTime? data) =>
      (super.noSuchMethod(
            Invocation.method(#getCronogramaByDate, [data]),
            returnValue: <_i3.CronogramaItem>[],
          )
          as List<_i3.CronogramaItem>);

  @override
  _i8.Future<bool> updateCronogramaItemStatus(
    String? itemId,
    _i3.StatusItem? novoStatus,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCronogramaItemStatus, [
              itemId,
              novoStatus,
            ]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> removePlano(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removePlano, [id]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i4.Materia> addMateria(
    String? nome,
    String? editalId,
    String? cargoId,
    int? nivelProficiencia,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addMateria, [
              nome,
              editalId,
              cargoId,
              nivelProficiencia,
            ]),
            returnValue: _i8.Future<_i4.Materia>.value(
              _FakeMateria_3(
                this,
                Invocation.method(#addMateria, [
                  nome,
                  editalId,
                  cargoId,
                  nivelProficiencia,
                ]),
              ),
            ),
          )
          as _i8.Future<_i4.Materia>);

  @override
  List<_i4.Materia> getMateriasByEditalAndCargo(
    String? editalId,
    String? cargoId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMateriasByEditalAndCargo, [
              editalId,
              cargoId,
            ]),
            returnValue: <_i4.Materia>[],
          )
          as List<_i4.Materia>);

  @override
  _i4.Materia? getMateriaById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getMateriaById, [id]))
          as _i4.Materia?);

  @override
  _i8.Future<bool> updateMateria(_i4.Materia? materia) =>
      (super.noSuchMethod(
            Invocation.method(#updateMateria, [materia]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> removeMateria(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeMateria, [id]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i5.Assunto> addAssunto(
    String? nome,
    String? materiaId,
    int? ordem,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addAssunto, [nome, materiaId, ordem]),
            returnValue: _i8.Future<_i5.Assunto>.value(
              _FakeAssunto_4(
                this,
                Invocation.method(#addAssunto, [nome, materiaId, ordem]),
              ),
            ),
          )
          as _i8.Future<_i5.Assunto>);

  @override
  List<_i5.Assunto> getAssuntosByMateria(String? materiaId) =>
      (super.noSuchMethod(
            Invocation.method(#getAssuntosByMateria, [materiaId]),
            returnValue: <_i5.Assunto>[],
          )
          as List<_i5.Assunto>);

  @override
  _i5.Assunto? getAssuntoById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getAssuntoById, [id]))
          as _i5.Assunto?);

  @override
  _i8.Future<bool> updateAssunto(_i5.Assunto? assunto) =>
      (super.noSuchMethod(
            Invocation.method(#updateAssunto, [assunto]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> marcarAssuntoComoEstudado(String? id, bool? isEstudado) =>
      (super.noSuchMethod(
            Invocation.method(#marcarAssuntoComoEstudado, [id, isEstudado]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> removeAssunto(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeAssunto, [id]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [IAService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAService extends _i1.Mock implements _i12.IAService {
  MockIAService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConfigured =>
      (super.noSuchMethod(Invocation.getter(#isConfigured), returnValue: false)
          as bool);

  @override
  String get apiType =>
      (super.noSuchMethod(
            Invocation.getter(#apiType),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#apiType),
            ),
          )
          as String);

  @override
  bool get forceCacheMode =>
      (super.noSuchMethod(
            Invocation.getter(#forceCacheMode),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void switchService(String? apiType) => super.noSuchMethod(
    Invocation.method(#switchService, [apiType]),
    returnValueForMissingStub: null,
  );

  @override
  void setApiType(String? apiType) => super.noSuchMethod(
    Invocation.method(#setApiType, [apiType]),
    returnValueForMissingStub: null,
  );

  @override
  void setForceCacheMode(bool? value) => super.noSuchMethod(
    Invocation.method(#setForceCacheMode, [value]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> initCache() =>
      (super.noSuchMethod(
            Invocation.method(#initCache, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<Map<String, dynamic>> setApiKey(String? apiKey, String? apiType) =>
      (super.noSuchMethod(
            Invocation.method(#setApiKey, [apiKey, apiType]),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  bool isWithinTokenLimit(String? texto) =>
      (super.noSuchMethod(
            Invocation.method(#isWithinTokenLimit, [texto]),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Future<bool> configurarApiKey(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#configurarApiKey, [apiKey]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> testApiKey(String? apiKey, String? apiType) =>
      (super.noSuchMethod(
            Invocation.method(#testApiKey, [apiKey, apiType]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<String> callApiWithPrompt(String? prompt) =>
      (super.noSuchMethod(
            Invocation.method(#callApiWithPrompt, [prompt]),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#callApiWithPrompt, [prompt]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  dynamic parseJsonResponse(String? jsonString) =>
      super.noSuchMethod(Invocation.method(#parseJsonResponse, [jsonString]));

  @override
  _i8.Future<Map<String, dynamic>?> gerarRespostaJson(String? prompt) =>
      (super.noSuchMethod(
            Invocation.method(#gerarRespostaJson, [prompt]),
            returnValue: _i8.Future<Map<String, dynamic>?>.value(),
          )
          as _i8.Future<Map<String, dynamic>?>);

  @override
  _i8.Future<List<_i3.Flashcard>> gerarFlashcards({
    required String? userId,
    String? editalId,
    required String? materia,
    required String? texto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#gerarFlashcards, [], {
              #userId: userId,
              #editalId: editalId,
              #materia: materia,
              #texto: texto,
            }),
            returnValue: _i8.Future<List<_i3.Flashcard>>.value(
              <_i3.Flashcard>[],
            ),
          )
          as _i8.Future<List<_i3.Flashcard>>);

  @override
  _i8.Future<String> analisarEditalPdf(
    _i13.Uint8List? pdfBytes, {
    String? pdfName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #analisarEditalPdf,
              [pdfBytes],
              {#pdfName: pdfName},
            ),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #analisarEditalPdf,
                  [pdfBytes],
                  {#pdfName: pdfName},
                ),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> extrairCargosEdital(
    _i13.Uint8List? pdfBytes, {
    String? pdfName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #extrairCargosEdital,
              [pdfBytes],
              {#pdfName: pdfName},
            ),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #extrairCargosEdital,
                  [pdfBytes],
                  {#pdfName: pdfName},
                ),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> extrairInfoBasicasEdital(
    _i13.Uint8List? pdfBytes, {
    String? pdfName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #extrairInfoBasicasEdital,
              [pdfBytes],
              {#pdfName: pdfName},
            ),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #extrairInfoBasicasEdital,
                  [pdfBytes],
                  {#pdfName: pdfName},
                ),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> extrairConcursoConteudo({
    required _i13.Uint8List? pdfBytes,
    required String? cargoAlvo,
    String? pdfName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#extrairConcursoConteudo, [], {
              #pdfBytes: pdfBytes,
              #cargoAlvo: cargoAlvo,
              #pdfName: pdfName,
            }),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#extrairConcursoConteudo, [], {
                  #pdfBytes: pdfBytes,
                  #cargoAlvo: cargoAlvo,
                  #pdfName: pdfName,
                }),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> extrairConteudoProgramatico({
    required _i13.Uint8List? pdfBytes,
    required String? cargoAlvo,
    String? pdfName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#extrairConteudoProgramatico, [], {
              #pdfBytes: pdfBytes,
              #cargoAlvo: cargoAlvo,
              #pdfName: pdfName,
            }),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#extrairConteudoProgramatico, [], {
                  #pdfBytes: pdfBytes,
                  #cargoAlvo: cargoAlvo,
                  #pdfName: pdfName,
                }),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> gerarResumo(String? texto) =>
      (super.noSuchMethod(
            Invocation.method(#gerarResumo, [texto]),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#gerarResumo, [texto]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> gerarEsquema({required String? texto, String? titulo}) =>
      (super.noSuchMethod(
            Invocation.method(#gerarEsquema, [], {
              #texto: texto,
              #titulo: titulo,
            }),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#gerarEsquema, [], {
                  #texto: texto,
                  #titulo: titulo,
                }),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> gerarQuestoes({
    required String? texto,
    required String? materia,
    required String? dificuldade,
    required int? quantidade,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#gerarQuestoes, [], {
              #texto: texto,
              #materia: materia,
              #dificuldade: dificuldade,
              #quantidade: quantidade,
            }),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#gerarQuestoes, [], {
                  #texto: texto,
                  #materia: materia,
                  #dificuldade: dificuldade,
                  #quantidade: quantidade,
                }),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> callApi(String? prompt) =>
      (super.noSuchMethod(
            Invocation.method(#callApi, [prompt]),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#callApi, [prompt]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> callGeminiApiWithPdf(
    String? prompt,
    _i13.Uint8List? pdfBytes, {
    String? pdfName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #callGeminiApiWithPdf,
              [prompt, pdfBytes],
              {#pdfName: pdfName},
            ),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #callGeminiApiWithPdf,
                  [prompt, pdfBytes],
                  {#pdfName: pdfName},
                ),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
